version: "3.9"
services:

  local:
    build:
      context: "."
      target: local
    image: traffic-app:local
    container_name: traffic-app-local
    env_file:
      - .env

  test: 
    build:
      context: "."
      target: test
    image: traffic-app:test
    container_name: traffic-app-test
    env_file:
      - .env